FROM aler9/rtsp-simple-server as build

FROM ubuntu:20.04

RUN apt update
RUN DEBIAN_FRONTEND=noninteractive apt install -y iputils-ping net-tools iproute2 apache2 curl iptables ethtool
RUN a2enmod cgi

COPY --from=build /rtsp-simple-server /usr/bin/rtsp-simple-server
COPY rtsp-simple-server.yml scripts/start.sh ./
COPY scripts/test.sh scripts/register.sh /usr/lib/cgi-bin/

CMD /start.sh
